### ISSUE TITLE
[BUG] Trying to run Qiskit teleportation circuit on "qbraid_qir_simulator"

### ISSUE THREAD

**Issue by xthecapx** [qBraid/qBraid#790]
### Environment

I have been trying to run Qiskit code on , but I'm getting an error, and I'm not sure what I'm doing wrong

```
File "/code/app/quantum/teleportation.py", line 87, in qbraid_teleportation_experiment
web-1  |     jobs = device.run(qiskit_circuit, shots=N)
web-1  |   File "/usr/local/lib/python3.10/site-packages/qbraid/runtime/native/device.py", line 268, in run
web-1  |     runtime_payload = {**aux_payload, **run_input_json}
web-1  | TypeError: 'QuantumCircuit' object is not a mapping
```

### Context

Yes

### What happened?

My code looks like:
```Python
def generate_random_u_params():
    # Generate theta between 0 and pi
    theta = np.random.uniform(0, np.pi)
    
    # Generate phi and lambda between 0 and 2*pi
    phi = np.random.uniform(0, 2*np.pi)
    lambda_ = np.random.uniform(0, 2*np.pi)
    
    return theta, phi, lambda_

def generate_teleportation_circuit():
    # Generate random U gate
    theta, phi, lambda_ = generate_random_u_params()

    # Create teleportation circuit
    qc = QuantumCircuit(3, 3)
    
    # Apply random U gate to the first qubit
    qc.u(theta, phi, lambda_, 0)
    
    # Create Bell pair
    qc.h(1)
    qc.cx(1, 2)
    
    # Teleportation protocol
    qc.cx(0, 1)
    qc.h(0)
    qc.measure([0, 1], [0, 1])
    qc.cx(1, 2)
    qc.cz(0, 2)
    
    # Apply inverse U gate
    qc.u(-theta, -lambda_, -phi, 2)
    
    # Measure the final state
    qc.measure(2, 2)

    return qc

qiskit_circuit = generate_teleportation_circuit()
provider = QbraidProvider()
devices = provider.get_devices()
device = provider.get_device("qbraid_qir_simulator")
jobs = device.run(qiskit_circuit, shots=N)
```

any suggestion?

**Comment by TheGupta2012** [comment]
Hey, I did not get the error which you had mentioned. Could you please specify which version of the qbraid-sdk you are using? I am using the following package versions - 

```bash
qbraid                        0.8.3
qbraid-core                   0.1.25
qbraid-qir                    0.2.2
qiskit                        1.2.0
qiskit-ibm-runtime            0.29.0
numpy                         2.1.1
```

**Comment by ryanhill1** [comment]
@xthecapx Seems like you're running in the qBraid Lab environment, which I believe is still on version 0.7.x. I will try to get that updated ASAP! That should resolve it

**Comment by ryanhill1** [comment]
> @xthecapx Seems like you're running in the qBraid Lab environment, which I believe is still on version 0.7.x. I will try to get that updated ASAP! That should resolve it

@xthecapx The qBraid-SDK environment (slug: `qbraid_sdk_9j9sjy`) is now up-to-date! Please login to [lab.qbraid.com](https://lab.qbraid.com), [uninstall](https://docs.qbraid.com/lab/user-guide/environments#uninstall-cancel-install-environment) your current version of the qBraid-SDK environment, and then [re-install](https://docs.qbraid.com/lab/user-guide/environments#install-environment) the environment to get the last version (v0.8.3). I tested it, and your qiskit teleportation circuit should then be able to run on the QIR simulator with no problems! Just make sure that the active [kernel](https://docs.qbraid.com/lab/user-guide/notebooks#switch-notebook-kernel) you're using in your notebook matches `Python 3 [qBraid-SDK]`. Let me know if you run into any more issues!

**Comment by xthecapx** [comment]
I'm pushing my changes in the following project https://github.com/xthecapx/qc_experiment, we have the intention to run an experiment in multiples providers and we would like to use qbraid.

Thanks for the answers, I was using, I'll update the version to see if it works!. My requirements are.

```
fastapi[standard]==0.115.0
pydantic-settings
ibm-cloud-sdk-core==3.20.3
ibm-platform-services==0.55.1
pandas==2.2.3
qiskit==1.2.1
qiskit-aer==0.15.0
qiskit-ibm-runtime==0.30.0
requests==2.32.3
qbraid==0.8.2
prometheus-fastapi-instrumentator==7.0.0
opentelemetry-distro==0.45b0
opentelemetry-instrumentation-fastapi==0.45b0
opentelemetry-instrumentation-logging==0.45b0
opentelemetry-exporter-otlp==1.24.0
```

**Comment by ryanhill1** [comment]
@xthecapx Ok, great! Yes, installing the latest qBraid-SDK environment should fix the issue... but if it doesn't let me know and I'll be happy to assist further.

**Comment by xthecapx** [comment]
I update the library, I got the same error but a little bit more elaborate:

```
[<qbraid.runtime.native.device.QbraidDevice('qbraid_qir_simulator')>]
{'device_id': 'qbraid_qir_simulator', 'simulator': True, 'num_qubits': 64, 'provider_name': 'qBraid', 'basis_gates': None, 'name': 'QIR sparse simulator', 'pricing': {'perTask': Credits('0.500'), 'perShot': Credits('0'), 'perMinute': Credits('7.500')}, 'queue_depth': 0, 'status': 'ONLINE', 'paradigm': 'gate_model', 'noise_models': ['ideal'], 'runtime_config': {'target_ir': None, 'conversion_scheme': {'conversion_graph': None, 'max_path_attempts': 3, 'max_path_depth': None}, 'options': {'transpile': True, 'transform': True, 'validate': 2}}}
INFO:     192.168.65.1:46810 - "GET /qbraid-teleportation/?executions=1 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 174, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 172, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 185, in __call__
    with collapse_excgroups():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 187, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/code/app/utils.py", line 77, in dispatch
    raise e from None
  File "/code/app/utils.py", line 72, in dispatch
    response = await call_next(request)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/code/app/main.py", line 87, in execute_qbraid_teleportation
    success_rate, counts = qbraid_teleportation_experiment(executions)
  File "/code/app/quantum/teleportation.py", line 87, in qbraid_teleportation_experiment
    jobs = device.run(qiskit_circuit, shots=N)
  File "/usr/local/lib/python3.10/site-packages/qbraid/runtime/native/device.py", line 306, in run
    runtime_payload = {**aux_payload, **run_input_json}
```

It looks like is failing here: `File "/code/app/quantum/teleportation.py", line 87, in qbraid_teleportation_experiment
    jobs = device.run(qiskit_circuit, shots=N)`

I using the Free account to see if I'm able to run this circuit. If I can demo this to my Professor we will use it for the experiment and we will buy some credits. The account I'm using is https://account.qbraid.com/profile/Thecap

**Comment by xthecapx** [comment]
I'm using the code I posted here https://github.com/xthecapx/qc_experiment. I'm getting a 500 because of `File "/code/app/quantum/teleportation.py", line 87, in qbraid_teleportation_experiment jobs = device.run(qiskit_circuit, shots=N)`. I'm not using the qBraid lab's by the qbraid-sdk in a Docker container. At the moment I'm running the container on my local, but the plan is to deploy the image to a server.

**Comment by xthecapx** [comment]
Thanks a lot for the help. your code works, however, after the changes I'm getting this error.

```
raise NodeNotFoundError(graph_type, source, graph.nodes())
qbraid.transpiler.exceptions.NodeNotFoundError: Provided conversion graph does not contain node 'tuple'. Supported nodes are: ['qiskit', 'qasm2', 'qasm3', 'openqasm3', 'ionq', 'pyqir']
```

**Comment by xthecapx** [comment]
I got the error, everything is working now, I got the message I dont have credits, which means I reach the server! thanks for the support!
